DEFAULT_WIDTH = 520
DEFAULT_HEIGHT = 640
MIN_WIDTH = 380
MIN_HEIGHT = 480
GRID_SIZE = 3

PLAYER_X = "X"
PLAYER_O = "O"
EMPTY = ""

# Theme
BG_COLOR = "#0d1b2a"
BOARD_BORDER_COLOR = "#778da9"
BOARD_FRAME_BG = "#1b263b"
CELL_BG = "#415a77"
CELL_HOVER_BG = "#4d6a85"
CELL_DISABLED_BG = "#2d3f55"

FG_TITLE = "#e0e1dd"
FG_SUBTITLE = "#8d99ae"
FG_STATUS = "#cad2c5"

PLAYER_X_COLOR = "#48cae4"
PLAYER_O_COLOR = "#f4a261"
WIN_HIGHLIGHT_BG = "#2a9d8f"
WIN_HIGHLIGHT_FG = "#ffffff"

BTN_NEW_GAME_BG = "#e76f51"
BTN_NEW_GAME_FG = "#ffffff"
BTN_NEW_GAME_ACTIVE = "#f4a261"

FONT_FAMILY = "DejaVu Sans"

# Base sizes at DEFAULT_WIDTH x DEFAULT_HEIGHT
FONT_SIZE_TITLE = 28
FONT_SIZE_SUBTITLE = 11
FONT_SIZE_STATUS = 14
FONT_SIZE_BADGE = 32
FONT_SIZE_CELL = 42
FONT_SIZE_SCORE = 12
FONT_SIZE_BUTTON = 13

FONT_SIZE_CELL_MIN = 14
FONT_SIZE_CELL_MAX = 160

# Font size as a fraction of the widget's smaller side (width/height)
FONT_TITLE_RATIO = 0.38
FONT_SUBTITLE_RATIO = 0.16
FONT_STATUS_RATIO = 0.38
FONT_BADGE_RATIO = 0.62
FONT_SCORE_RATIO = 0.42
FONT_BUTTON_RATIO = 0.32
FONT_CELL_RATIO = 0.58

# Vertical space share for each section (must sum to 100)
LAYOUT_WEIGHT_HEADER = 14
LAYOUT_WEIGHT_STATUS = 11
LAYOUT_WEIGHT_BOARD = 52
LAYOUT_WEIGHT_FOOTER = 23

CELL_GAP = 3
